name: terraform-build.yaml-$(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)

trigger: none

parameters:
  - name: ServiceConnection
    type: string
    default: "spn-libd-uks-dev-mgmt-01"
    displayName: 'Azure DevOps Service Connection'
    values:
      - "spn-libd-uks-dev-mgmt-01-client-secret-enabled"
      - "spn-libd-uks-dev-mgmt-01"
      - "fedcred-msi-azdo-libredevops-4a23d149-8cee-4643-a57b-3b3db30e54ce"
      - "msi-azdo-libredevops-4a23d149-8cee-4643-a57b-3b3db30e54ce"
      - "uid-libd-uks-dev-mgmt-01"

  - name: TerraformCodeLocation
    type: string
    default: 'examples'
    displayName: 'Terraform Code Directory Path'

  - name: TerraformStackToRunJson
    type: string
    default: '["module-development"]'
    values:
      - '["rg"]'
      - '["network"]'
      - '["azdo-pipelines-setup"]'
      - '["rg", "network"]'
      - '["module-development"]'
      - '["all"]'
    displayName: 'Terraform Stacks to Run'

  - name: TerraformWorkspace
    type: string
    default: 'dev'
    displayName: 'Terraform Workspace Name'

  - name: CheckovSkipCheck
    type: string
    default: 'CKV2_AZURE_31'
    displayName: 'Checkov Skip Checks (Comma-Separated)'

  - name: DebugMode
    type: string
    values: [ "true", "false" ]
    default: "false"
    displayName: "Debug mode enabled"

  - name: TerraformInitExtraArgsJson
    type: string
    default: >
      [
        "-upgrade",
        "-backend-config=subscription_id=$(TF_VAR_ARM_BACKEND_SUBSCRIPTION_ID)",
        "-backend-config=resource_group_name=$(TF_VAR_ARM_BACKEND_STORAGE_RG_NAME)",
        "-backend-config=storage_account_name=$(TF_VAR_ARM_BACKEND_STORAGE_ACCOUNT)",
        "-backend-config=container_name=$(TF_VAR_ARM_BACKEND_CONTAINER_NAME)"
      ]
    displayName: 'Extra Args for terraform init'

  - name: TerraformPlanExtraArgsJson
    type: string
    default: '[ ]'
    displayName: 'Extra Args for terraform plan'

  - name: AzureDevOpsPoolName
    type: string
    default: "Default"
    values:
      - "Default"
      - "Azure Pipelines"
      - "vmss-libd-uks-dev-02"
    displayName: 'The Pool Name for the Job to run on'

  - name: AzurePipelinesVmImage
    type: string
    default: 'ubuntu-latest'
    displayName: 'If Azure Pipelines is selected, which vmImage to run'

  - name: dependsOnStages
    displayName: "Depends On"
    type: object
    default: [ ]

resources:
  repositories:
    - repository: githubTemplates
      type: github
      name: libre-devops/terraform-azure-azdo-pipeline-templates
      ref: main
      endpoint: libredevops


variables:
  - group: terraform-${{ parameters.TerraformWorkspace }}-vars

stages:
  - template: .azuredevops/templates/stages/terraform-init-plan-apply.yaml@githubTemplates
    parameters:
      ServiceConnection: ${{ parameters.ServiceConnection }}
      TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}
      TerraformStackToRunJson: ${{ parameters.TerraformStackToRunJson }}
      TerraformWorkspace: ${{ parameters.TerraformWorkspace }}
      CheckovSkipCheck: ${{ parameters.CheckovSkipCheck }}
      DebugMode: ${{ parameters.DebugMode }}
      TerraformInitExtraArgsJson: ${{ parameters.TerraformInitExtraArgsJson }}
      TerraformPlanExtraArgsJson: ${{ parameters.TerraformPlanExtraArgsJson }}
      AzureDevOpsPoolName: ${{ parameters.AzureDevOpsPoolName }}
      dependsOnStages: ${{ parameters.dependsOnStages }}
